version: '2'
services:
  node:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: node.dockerfile
    image: &node-image demo-saleseng-gatsby-cli # this image will be reused as `NODE_IMAGE` in subsequent Docker builds
    labels:
      lagoon.type: node
    volumes:
      - .:/app:delegated
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=3000
      - LAGOON_ROUTE=http://demo-saleseng-gatsby-node.docker.amazee.io

  # SERVICE: NGINX container for hosting the static gatsby files
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        NODE_IMAGE: *node-image # Inject the name of the node image
    depends_on:
      - node
    labels:
      lagoon.type: nginx
    environment:
      - LAGOON_ROUTE=http://demo-saleseng-gatsby-nginx.docker.amazee.io
    networks:
      - amazeeio-network
      - default

networks:
  amazeeio-network:
    external: true
